### ISSUE TITLE
SimpleUc (Sorry to post that here).

### ISSUE THREAD

**Issue by TheIntelloBox** [Minecrell/TerminalConsoleAppender#1]
Hello ! :(

Please Minecrell, could you just fix in your plugin SimpleUc, the error with Metrics, because it spamming my console ? :(
Thanks !

I love this plugin. :)

The error : [12:28:25] [Craft Scheduler Thread - 22/WARN]: [SimpleUc] Plugin SimpleUc v1.4.5 generated an exception while executing task 68
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.mcstats.MetricsLite.postPlugin(MetricsLite.java:285) ~[?:?]
	at org.mcstats.MetricsLite.access$200(MetricsLite.java:51) ~[?:?]
	at org.mcstats.MetricsLite$1.run(MetricsLite.java:173) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-7d78b81-e232e15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

Thanks !
Have a nice day !
TheIntelloBox.

**Comment by Minecrell** [comment]
I'm sorry, but I've stopped maintaining SimpleUc several years ago, mostly because similar features exist in the Spigot configuration.

You can try the following to fix it:

- Opt-out of Metrics in `plugins/PluginMetrics/config.yml` (set `opt-out` to `true`)
- You might be able to fix the plugin yourself using the solution provided in https://www.spigotmc.org/threads/minecraft-1-9-release.127186/ (See "CraftBukkit")

In the future please contact me via mail (see my GitHub profile), or via PM on Spigot/BukkitDev instead of opening issues on unrelated repositories. Thanks!
