### ISSUE TITLE
Issue with log4j 2.18.0

### ISSUE THREAD

**Issue by bundabrg** [Minecrell/TerminalConsoleAppender#25]
The last working log4j is 2.17.1.

If using 2.18.0 I receive the following stack trace:
```
2022-09-04 20:05:35,751 main WARN The style attribute disableAnsi=false is incorrect. java.lang.IllegalArgumentException: No enum constant org.apache.logging.log4j.core.pattern.AnsiEscape.DISABLEANSI=FALSE
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at org.apache.logging.log4j.util.EnglishEnums.valueOf(EnglishEnums.java:67)
        at org.apache.logging.log4j.util.EnglishEnums.valueOf(EnglishEnums.java:50)
        at org.apache.logging.log4j.core.pattern.AnsiEscape.createSequence(AnsiEscape.java:486)
        at org.apache.logging.log4j.core.pattern.StyleConverter.newInstance(StyleConverter.java:96)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:590)
        at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:657)
        at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:420)
        at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:177)
        at org.apache.logging.log4j.core.layout.PatternLayout$SerializerBuilder.build(PatternLayout.java:473)
        at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:139)
        at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:60)
        at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:766)
        at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:626)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1133)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1058)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1050)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1050)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:659)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:257)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:303)
        at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:694)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:711)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
        at au.com.grieve.reversion.platform.standalone.Standalone.<clinit>(Standalone.java:49)
```

## log4j.xml
```
<Configuration status="WARN">
    <Appenders>
        <TerminalConsole name="TerminalConsole">
            <PatternLayout pattern="[%d{HH:mm:ss} %style{%highlight{%-5level}{FATAL=red dim, ERROR=red, WARN=yellow bright, INFO=cyan bright, DEBUG=green, TRACE=white}}] %msg%n" disableAnsi="${tca:disableAnsi}"/>
        </TerminalConsole>


        <RollingRandomAccessFile name="File" fileName="logs/latest.log" filePattern="logs/%d{yyyy-MM-dd}-%i.log.gz">
            <PatternLayout pattern="%d{yyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
            <Policies>
                <TimeBasedTriggeringPolicy/>
                <OnStartupTriggeringPolicy/>
            </Policies>
        </RollingRandomAccessFile>
    </Appenders>

    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="TerminalConsole"/>
            <AppenderRef ref="File"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by stephan-gh** [comment]
Does it work if you remove the `disableAnsi="..."`?

**Comment by bundabrg** [comment]
It has the same issue. I suspect if its missing it just adds it by default.

**Comment by stephan-gh** [comment]
TCA does not add anything by default. I think the root problem is that your configuration is invalid: Why do you nest `%style` and `%highlight`? Dropping `%style{...}` around the `%highlight` fixes the error.

**Comment by bundabrg** [comment]
Thanks for that. It was something used for a long time that I inherited and I suspect the version change may just have become stricter and started throwing errors. I appreciate the attention to the issue.
