### ISSUE TITLE
Error while reading line

### ISSUE THREAD

**Issue by Exceptionflug** [Minecrell/TerminalConsoleAppender#3]
```
2017-10-10 00:43:40,453 main ERROR An exception occurred processing Appender Console java.lang.IllegalStateException
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:651)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:265)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
        at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1994)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1966)
        at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1303)
        at de.dawnstudios.nnxcloud.main.Main.launch(Main.java:142)
        at de.dawnstudios.nnxcloud.main.Main.main(Main.java:40)
```

**Comment by kashike** [comment]
#2

**Comment by Exceptionflug** [comment]
Oh how could I miss that...
