### ISSUE TITLE
Race condition when logging message while JLine is not reading input

### ISSUE THREAD

**Issue by stephan-gh** [Minecrell/TerminalConsoleAppender#4]
Related to https://github.com/WaterfallMC/Waterfall/issues/188, https://github.com/PaperMC/Paper/issues/1093

There is a possible race condition when logging a message using TerminalConsoleAppender, while the JLine `LineReader` is changing state (e.g. shortly before it starts reading or shortly after).

This results in an error when re-drawing the input prompt:

https://github.com/Minecrell/TerminalConsoleAppender/blob/b10535928a75673f3ddb3b8fbbf3fcaad41ef67d/src/main/java/net/minecrell/terminalconsole/TerminalConsoleAppender.java#L263-L267

```
ERROR An exception occurred processing Appender TerminalConsole java.lang.IllegalStateException
	at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:651)
	at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:265)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
```

**Comment by stephan-gh** [comment]
Related: https://github.com/jline/jline3/issues/292
