### ISSUE TITLE
Unable to run TerminalConsoleAppender under Cmder/ConEmu 

### ISSUE THREAD

**Issue by NickAcPT** [Minecrell/TerminalConsoleAppender#5]
Cmder is a great alternative to the command line on computers running versions older than Windows 10.

Cmder is a console emulator and uses ConEmu as it's base. This means the problems just need to be fixed with ConEmu and Cmder will work correctly.

I got this error whilst trying to run a Waterfall server.

Here's the full log:
```
[20:06:15 INFO]: Using standard Java JCE cipher.
[20:06:15 INFO]: Using standard Java compressor.
[20:06:15 INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.13-SNAPSHOT:92eb8b4:209
[20:06:16 INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
[20:06:16 INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())

[20:06:16 INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())

[20:06:16 INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())

[20:06:16 INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
[20:06:16 INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
[20:06:16 INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Loaded plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Loaded plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
[20:06:16 INFO]: Loaded plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Loaded plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Loaded plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 WARN]: Forced host server pvp is not defined
[20:06:16 INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO]: Enabled plugin cmd_find version git:cmd_find:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:16 INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[20:06:17 INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[20:06:17 INFO]: Enabled plugin FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432 by games647, http://github.com/games647/FastLogin/graphs/contributors
[20:06:17 INFO]: Enabled plugin cmd_server version git:cmd_server:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:17 INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:17 INFO]: Enabled plugin cmd_send version git:cmd_send:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:17 INFO]: Enabled plugin cmd_list version git:cmd_list:1.13-SNAPSHOT:92eb8b4:209 by WaterfallMC
[20:06:17 INFO]: Listening on /0.0.0.0:25566
[20:06:18 ERROR]: Exception in thread "main" com.sun.jna.LastErrorException: [127] The specified procedure could not be found.
[20:06:18 ERROR]:       at com.sun.jna.Native.invokeVoid(Native Method)
[20:06:18 ERROR]:       at com.sun.jna.Function.invoke(Function.java:408)
[20:06:18 ERROR]:       at com.sun.jna.Function.invoke(Function.java:354)
[20:06:18 ERROR]:       at com.sun.jna.Library$Handler.invoke(Library.java:244)
[20:06:18 ERROR]:       at org.jline.terminal.impl.jna.win.$Proxy16.SetConsoleMode(Unknown Source)
[20:06:18 ERROR]:       at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.setConsoleMode(JnaWinSysTerminal.java:89)
[20:06:18 ERROR]:       at org.jline.terminal.impl.AbstractWindowsTerminal.updateConsoleMode(AbstractWindowsTerminal.java:206)
[20:06:18 ERROR]:       at org.jline.terminal.impl.AbstractWindowsTerminal.setAttributes(AbstractWindowsTerminal.java:192)
[20:06:18 ERROR]:       at org.jline.terminal.impl.AbstractTerminal.enterRawMode(AbstractTerminal.java:123)
[20:06:18 ERROR]:       at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:512)
[20:06:18 ERROR]:       at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
[20:06:18 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157)
[20:06:18 ERROR]:       at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140)
[20:06:18 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:61)
[20:06:18 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

Oddly enough, this doesn't happen whilst running Paper

**Comment by jamierocks** [comment]
To be honest, that sounds like more of an issue with either jline or your console emulator.

**Comment by stephan-gh** [comment]
Related upstream bug: https://github.com/jline/jline3/issues/276 (although the error is slightly different the stack trace is exactly the same...) Not sure why it's not happening on Paper, are you using the latest version? It might have been introduced with the update to JLine 3.9.0.

Also, can you share the Windows version you're testing this on?

Anyway, closing this here for now since this is not a TCA problem but rather a problem in JLine.
